services:
  sparkbyte-site:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_VERSION: 24.14.0-alpine
        NGINX_VERSION: alpine3.22
    image: sparkbyte-site
    container_name: sparkbyte-site
    ports:
      - "8080:8080"
    restart: unless-stopped
